// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tpgsmxvsqgzdtrowreqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwZ3NteHZzcWd6ZHRyb3dyZXF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4ODMyMTcsImV4cCI6MjA1NzQ1OTIxN30.JKSHzLaz5xZfIj85ok166ZsbXamQpkzUcbuLpxSBkv0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);